---
title: "Session 4 Part 2"
author: "Riley Sansone"
date: "2023-01-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r session 4 part 2}
#header = T signifies that what we are having it read contains labels, sep ="\" separates the table columns with tab
data1 = read.table("https://raw.githubusercontent.com/enosnas/DSO-458/main/Companies.txt",header = T,sep ="\t")

head(data1)
tail(data1)

dim(data1)

data2 = read.csv("https://raw.githubusercontent.com/enosnas/DSO-458/main/Companies.csv", header = T)

head(data2)
tail(data2)
dim(data2)

install.packages("readxl")
library(readxl)

data = read_excel("Companies.xlsx")
dim(data)
View(data)

#shows current names of the columns in the excel file
colnames(data)

#rename the column names using a vector
colnames(data) = c("Name","Assets","NetIncome","Employees")
colnames(data)
summary(data)

#find out what type of data we are looking at
class(data)

#data frames are different from matrices as data frame objects can have non-numeric columns
?data.frame

#access info from an individual column
data[ ,3]
#can also do it this way
data$NetIncome
#Make a RoA column
data$Return.on.Asset = data$NetIncome/data$Assets

View(data)

#Now we'll make an income of employee column
data$Income.per.Employee = data$NetIncome/data$Employees

#saving data to a .csv is easiest way to save data and share with others
write.csv(data,file = "Companies_Updated.csv")

#find mean of assets
mean(data$Assets)

#minimum return of assets
min(data$Return.on.Asset)

#find highest productivity company using income per employee
max(data$Income.per.Employee)
#set the highest productivity equal to a variable
max.productivity = max(data$Income.per.Employee)
#specify that we want information from the first column
data[ ,1]
# == means comparison, not setting it equal to, this tells us if the companies match the highest productivity but in a true false data set which is not helpful since we have to look for the name still
data$Income.per.Employee == max.productivity
#we set this information as a variable called condition to easily reference it
condition = data$Income.per.Employee == max.productivity
#by putting condition into the data function and a 1 after it, we search column 1's names to find the one that matches the true statement for highest productivity
data[condition,1]

#find companies with higher than median return on assets
med_roa = median(data$Return.on.Asset)
med_roa
#create a variable (condition) for this information and see which companies match in true or false dataset
cond = data$Return.on.Asset > med_roa
cond

#create a subset list of data for this data, 83 companies match the condition
subset1 = data[cond, ]
dim(subset1)

#see what datasets we have loaded
data()

install.packages("astsa")
library(astsa)
#check the datasets in the package astsa
data(package="astsa")
#see information on a dataset in astsa called gas
?gas
gas
#check the class, it is ts which means time series
class(gas)

plot(gas)
mean(gas)

#take out a subset of the data, first four weeks of data in this case
gas[1:4]

data(package="datasets")
#find the dataset on JnJ
?JohnsonJohnson

data("JohnsonJohnson")

plot(JohnsonJohnson)
```
